server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 111111

  resources:
    static-locations: classpath:/templates  #访问静态页面